const sampleListings = [
  {
    title: "Demo Stay near Vidhana Soudha",
    description: "A sample city stay for exploring Bengaluru, with the Vidhana Soudha landmark and central-city attractions nearby.",
    image: { url: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1000&q=85", filename: "bengaluru-vidhana-soudha" },
    price: 3200,
    location: "Bengaluru, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Mysuru",
    description: "A sample heritage-inspired base for visiting Mysuru Palace, Devaraja Market, and the city's historic centre.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "mysuru-palace" },
    price: 2800,
    location: "Mysuru, Karnataka",
    country: "India",
  },
  {
    title: "Demo Coffee Country Stay",
    description: "A sample countryside stay in Kodagu, surrounded by the coffee-growing landscape and forested hills near Madikeri.",
    image: { url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=85", filename: "madikeri-coffee-country" },
    price: 4100,
    location: "Madikeri, Karnataka",
    country: "India",
  },
  {
    title: "Demo Hill Stay in Chikkamagaluru",
    description: "A sample hill-country stay for exploring Chikkamagaluru's coffee estates and the Western Ghats around Mullayanagiri.",
    image: { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85", filename: "chikkamagaluru-western-ghats" },
    price: 3600,
    location: "Chikkamagaluru, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Hampi",
    description: "A sample stay for visiting the boulder-strewn Hampi landscape and the historic Virupaksha Temple area.",
    image: { url: "https://images.unsplash.com/photo-1600100397608-f0109c2d7b17?auto=format&fit=crop&w=1000&q=85", filename: "hampi-heritage-landscape" },
    price: 2400,
    location: "Hampi, Karnataka",
    country: "India",
  },
  {
    title: "Demo Coastal Stay in Gokarna",
    description: "A sample coastal base for walks along Gokarna's Arabian Sea shoreline and visits to Om Beach.",
    image: { url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1000&q=85", filename: "gokarna-coast" },
    price: 2900,
    location: "Gokarna, Karnataka",
    country: "India",
  },
  {
    title: "Demo Beach Stay near Malpe",
    description: "A sample beachside stay for exploring Malpe Beach, the Udupi coast, and nearby St. Mary's Islands boat trips.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85", filename: "malpe-beach-udupi" },
    price: 2700,
    location: "Udupi, Karnataka",
    country: "India",
  },
  {
    title: "Demo Western Ghats Stay",
    description: "A sample nature stay in Sakleshpur, with access to the green Western Ghats, wooded trails, and plantation country.",
    image: { url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85", filename: "sakleshpur-western-ghats" },
    price: 3300,
    location: "Sakleshpur, Karnataka",
    country: "India",
  },
  {
    title: "Demo Nature Stay in Kabini",
    description: "A sample nature-focused base in the Kabini region, known for its river, forests, and wildlife habitat.",
    image: { url: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1000&q=85", filename: "kabini-wildlife" },
    price: 5200,
    location: "Kabini, Karnataka",
    country: "India",
  },
  {
    title: "Demo Riverside Stay in Dandeli",
    description: "A sample riverside base for experiencing the Kali River, forest scenery, and outdoor activities around Dandeli.",
    image: { url: "https://images.unsplash.com/photo-1437482078695-73f5ca6c96e2?auto=format&fit=crop&w=1000&q=85", filename: "dandeli-kali-river" },
    price: 3100,
    location: "Dandeli, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Badami",
    description: "A sample stay for exploring Badami's sandstone cave temples and the dramatic red-rock cliffs around Agastya Lake.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "badami-cave-temples" },
    price: 2300,
    location: "Badami, Karnataka",
    country: "India",
  },
  {
    title: "Demo Temple-Town Stay in Aihole",
    description: "A sample village stay for visiting Aihole's historic temple complex and early Chalukya architecture.",
    image: { url: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=85", filename: "aihole-temples" },
    price: 2100,
    location: "Aihole, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Belur",
    description: "A sample stay near Belur's celebrated Chennakeshava Temple and the historic towns of the Hassan district.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "belur-chennakeshava-temple" },
    price: 2500,
    location: "Belur, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Halebidu",
    description: "A sample base for seeing Halebidu's Hoysaleswara Temple and the intricately carved Hoysala heritage nearby.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "halebidu-hoysaleswara-temple" },
    price: 2500,
    location: "Halebidu, Karnataka",
    country: "India",
  },
  {
    title: "Demo Fort-City Stay in Bidar",
    description: "A sample city stay for exploring Bidar Fort, its historic gateways, and the Deccan heritage quarter.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "bidar-fort" },
    price: 2200,
    location: "Bidar, Karnataka",
    country: "India",
  },
  {
    title: "Demo Heritage Stay in Vijayapura",
    description: "A sample stay in Vijayapura, a convenient base for visiting the landmark Gol Gumbaz and historic Deccan monuments.",
    image: { url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1000&q=85", filename: "vijayapura-gol-gumbaz" },
    price: 2600,
    location: "Vijayapura, Karnataka",
    country: "India",
  },
  {
    title: "Demo Waterfall Country Stay",
    description: "A sample countryside stay near Sagara for visiting Jog Falls and exploring the Western Ghats of Shivamogga district.",
    image: { url: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1000&q=85", filename: "jog-falls-sagara" },
    price: 3000,
    location: "Sagara, Karnataka",
    country: "India",
  },
  {
    title: "Demo Hilltop Stay near Nandi Hills",
    description: "A sample hill-country stay near Nandi Hills, known for its elevated viewpoints and sunrise over the Deccan plateau.",
    image: { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85", filename: "nandi-hills" },
    price: 3400,
    location: "Nandi Hills, Karnataka",
    country: "India",
  },
  {
    title: "Demo Coastal City Stay in Mangaluru",
    description: "A sample coastal city stay for exploring Mangaluru's beaches, local markets, and Tulu and Konkani food culture.",
    image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85", filename: "mangaluru-coast" },
    price: 2900,
    location: "Mangaluru, Karnataka",
    country: "India",
  },
  {
    title: "Demo Beach Stay near Murudeshwar",
    description: "A sample coastal base near Murudeshwar's beach, Arabian Sea views, and the well-known Shiva temple complex.",
    image: { url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1000&q=85", filename: "murudeshwar-coast" },
    price: 3100,
    location: "Murudeshwar, Karnataka",
    country: "India",
  },
];

module.exports = { data: sampleListings };
